#
# This file is structured to be consumed by both humans and computers.
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Community Advocates"
  text = """
This file lists the Community Advocates for the Chef project.  Community
Advocates may be assigned for each area where the community convenes online
(IRC, email list, GitHub, etc.).  Community Advocates are volunteers who have
the best interests of our community in mind.  They act in good faith to help
enforce our community guidelines and respond to incidents when they occur.

More information can be found in the [Chef Community Guidelines](https://github.com/chef/chef-rfc/blob/master/rfc020-community-guidelines.md).
"""

[Org]
  [Org.Lead]
    title = "Decider"
    person = "adamhjk"

  [Org.Ombudsperson]
    title = "Ombudsperson"
    person = "nathenharvey"


  [Org.Advocates]
    [Org.Advocates.ChefIRC]
      title = "#chef IRC"
      advocates = [
        "jonlives",
        "zts"
      ]
    [Org.Advocates.ChefHackingIRC]
      title = "#chef-hacking IRC"
      advocates = [
        "jonlives",
        "zts"
      ]
    [Org.Advocates.Serverfault]
      title = "Server Fault"
      advocates = [
        "miketheman"
      ]
    [Org.Advocates.ChefMailingList]
      title = "chef@ mailing list"
      advocates = [
        "vacant"
      ]
    [Org.Advocates.ChefDevMailingList]
      title = "chef-dev@ mailing list"
      advocates = [
        "vacant"
      ]
    [Org.Advocates.GitHub]
      title = "GitHub"
      advocates = [
        "vacant"
      ]
    [Org.Advocates.Stackoverflow]
      title = "Stack Overflow"
      advocates = [
        "vacant"
      ]
    [Org.Advocates.LinkedIn]
      title = "Chef LinkedIn Group"
      advocates = [
        "vacant"
      ]
    [Org.Advocates.Reddit]
      title = "Chef_Opscode Reddit ([https://www.reddit.com/r/chef_opscode/](https://www.reddit.com/r/chef_opscode/))"
      advocates = [
        "vacant"
      ]


[people]
  [people.adamhjk]
    Name = "Adam Jacob"
    GitHub = "adamhjk"
    IRC = "holoway"

  [people.nathenharvey]
    Name = "Nathen Harvey"
    GitHub = "nathenharvey"
    Twitter = "nathenharvey"
    IRC = "nathenharvey"
    email = "nharvey@chef.io"
    Phone = "+1-202-368-7264"

  [people.jonlives]
    Name = "Jon Cowie"
    GitHub = "jonlives"
    IRC = "jonlives"

  [people.zts]
    Name = "Zac Stevens"
    GitHub = "zts"
    IRC = "zts"

  [people.miketheman]
    Name = "Mike Fiedler"
    GitHub = "miketheman"
    ServerFault = "http://serverfault.com/users/7309/mike-fiedler"

  [people.vacant]
    Name = "Vacant - Submit a PR to become a Chef Community Advocate"
